config/routes.rb
Rails.application.routes.draw do
  resources :categoria
  resources :ahorros
  get 'dashboard/dashboard'
  resources :model_visita
  resources :lugars
  devise_for :models, controllers: {
    registrations: 'models/registrations'
  }
  resources :widgets
  resources :models do 
    member do 
      get :confirm_email
    end
  end

  root 'welcome#index'

end

app/models/lugar.rb
class Lugar < ApplicationRecord
    has_one_attached :image_place
end

app/controllers/lugars_controller.rb
class LugarsController < ApplicationController
  before_action :set_lugar, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'
  # GET /lugars
  # GET /lugars.json
  def index
    @lugars = Lugar.all
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # GET /lugars/1
  # GET /lugars/1.json
  def show
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # GET /lugars/new
  def new
    @lugar = Lugar.new
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # GET /lugars/1/edit
  def edit
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # POST /lugars
  # POST /lugars.json
  def create
    @lugar = Lugar.new(lugar_params)
    respond_to do |format|
      if @lugar.save
        format.html { redirect_to @lugar, notice: 'Lugar was successfully created.' }
        format.json { render :show, status: :created, location: @lugar }
      else
        format.html { render :new }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugars/1
  # PATCH/PUT /lugars/1.json
  def update
    respond_to do |format|
      if @lugar.update(lugar_params)
        format.html { redirect_to @lugar, notice: 'Lugar was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugar }
      else
        format.html { render :edit }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugars/1
  # DELETE /lugars/1.json
  def destroy
    @lugar.destroy
    respond_to do |format|
      format.html { redirect_to lugars_url, notice: 'Lugar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lugar
      @lugar = Lugar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lugar_params
      params.require(:lugar).permit(:id_pais, :nombre,:image_place,:id_usuario)
    end
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/views/lugars/_form.html.erb
<%= form_with(model: lugar, local: true) do |form| %>
  <% if lugar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lugar.errors.count, "error") %> prohibited this lugar from being saved:</h2>

      <ul>
      <% lugar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </p>
<% if lugar.image_place.attached? %>
    <%= image_tag lugar.image_place.variant(resize: "200x200!") , class: 'user-avatar' %>
<% end %>
<div class="field">
  
    <%= form.label 'Image' %><br />
     <%= form.file_field :image_place%>
</div>
 <div class="field">
    <%= form.label 'Country' %><br />
     <%= form.collection_select :id_pais, Country.order(:id),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>
  <div class="field">
    <%= form.hidden_field :id_usuario, :value => @user.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lugars/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', lugar: @lugar %>

<%= link_to  lugars_path, method: :get,class: 'button-cool' do %>
	<i class="fas fa-backward"></i>
<% end %>

app/views/lugars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lugars</h1>

<table>
  <thead>
    <tr>
      <th>Id pais</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lugars.each do |lugar| %>
      <tr>
        <td><%= lugar.id_pais %></td>
        <td><%= lugar.nombre %></td>
        <td><%= link_to 'Show', lugar %></td>
        <td><%= link_to 'Edit', edit_lugar_path(lugar) %></td>
        <td><%= link_to 'Destroy', lugar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lugar', new_lugar_path %>

app/views/lugars/new.html.erb
<h1>New Place</h1>

<%= render 'form', lugar: @lugar %>

<%= link_to  lugars_path, method: :get,class: 'button-cool' do %>
	<i class="fas fa-backward"></i>
<% end %>

app/views/lugars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id pais:</strong>
  <%= @lugar.id_pais %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @lugar.nombre %>
</p>

<%= link_to 'Edit', edit_lugar_path(@lugar) %> |
<%= link_to 'Back', lugars_path %>