config/routes.rb
Rails.application.routes.draw do
  resources :categoria
  resources :ahorros
  get 'dashboard/dashboard'
  resources :model_visita
  resources :lugars
  devise_for :models, controllers: {
    registrations: 'models/registrations'
  }
  resources :widgets
  resources :models do 
    member do 
      get :confirm_email
    end
  end

  root 'welcome#index'

end

app/models/ahorro.rb
class Ahorro < ApplicationRecord
end

app/controllers/ahorros_controller.rb
class AhorrosController < ApplicationController
  before_action :set_ahorro, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'
  # GET /ahorros
  # GET /ahorros.json
  def index
    @ahorros = Ahorro.all
  end

  # GET /ahorros/1
  # GET /ahorros/1.json
  def show
  end

  # GET /ahorros/new
  def new
    @ahorro = Ahorro.new
  end

  # GET /ahorros/1/edit
  def edit
  end

  # POST /ahorros
  # POST /ahorros.json
  def create
    @ahorro = Ahorro.new(ahorro_params)

    respond_to do |format|
      if @ahorro.save
        format.html { redirect_to "/#dashboard", notice: 'Ahorro was successfully created.' }
        format.json { render :show, status: :created, location: @ahorro }
      else
        format.html { render :new }
        format.json { render json: @ahorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ahorros/1
  # PATCH/PUT /ahorros/1.json
  def update
    respond_to do |format|
      if @ahorro.update(ahorro_params)
        format.html { redirect_to "/#dashboard", notice: 'Ahorro was successfully updated.' }
        format.json { render :show, status: :ok, location: @ahorro }
      else
        format.html { render :edit }
        format.json { render json: @ahorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ahorros/1
  # DELETE /ahorros/1.json
  def destroy
    @ahorro.destroy
    respond_to do |format|
      format.html { redirect_to ahorros_url, notice: 'Ahorro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ahorro
      @ahorro = Ahorro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ahorro_params
      params.require(:ahorro).permit(:id_viaje, :fecha_deposito, :cantidad)
    end
end

app/helpers/ahorros_helper.rb
module AhorrosHelper
end

app/views/ahorros/_form.html.erb
<%= form_with(model: ahorro, local: true) do |form| %>
  <% if ahorro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ahorro.errors.count, "error") %> prohibited this ahorro from being saved:</h2>

      <ul>
      <% ahorro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_viaje %>
    <%= form.number_field :id_viaje %>
  </div>

  <div class="field">
    <%= form.label :fecha_deposito %>
    <%= form.date_select :fecha_deposito %>
  </div>

  <div class="field">
    <%= form.label :numero_depostio %>
    <%= form.number_field :numero_depostio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ahorros/edit.html.erb
<h1>Editing Ahorro</h1>

<%= render 'form', ahorro: @ahorro %>

<%= link_to 'Show', @ahorro %> |
<%= link_to 'Back', ahorros_path %>

app/views/ahorros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ahorros</h1>

<table>
  <thead>
    <tr>
      <th>Id viaje</th>
      <th>Fecha deposito</th>
      <th>Numero depostio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ahorros.each do |ahorro| %>
      <tr>
        <td><%= ahorro.id_viaje %></td>
        <td><%= ahorro.fecha_deposito %></td>
        <td><%= ahorro.numero_depostio %></td>
        <td><%= link_to 'Show', ahorro %></td>
        <td><%= link_to 'Edit', edit_ahorro_path(ahorro) %></td>
        <td><%= link_to 'Destroy', ahorro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ahorro', new_ahorro_path %>

app/views/ahorros/new.html.erb
<h1>New Ahorro</h1>

<%= render 'form', ahorro: @ahorro %>

<%= link_to 'Back', ahorros_path %>

app/views/ahorros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id viaje:</strong>
  <%= @ahorro.id_viaje %>
</p>

<p>
  <strong>Fecha deposito:</strong>
  <%= @ahorro.fecha_deposito %>
</p>

<p>
  <strong>Numero depostio:</strong>
  <%= @ahorro.numero_depostio %>
</p>

<%= link_to 'Edit', edit_ahorro_path(@ahorro) %> |
<%= link_to 'Back', ahorros_path %>