config/routes.rb
Rails.application.routes.draw do
  resources :categoria
  resources :ahorros
  get 'dashboard/dashboard'
  resources :model_visita
  resources :lugars
  devise_for :models, controllers: {
    registrations: 'models/registrations'
  }
  resources :widgets
  resources :models do 
    member do 
      get :confirm_email
    end
  end

  root 'welcome#index'

end

app/models/ahorro.rb
class Ahorro < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
    self.table_name = "avatars"
end

app/models/categoria.rb
class Categoria < ApplicationRecord
    belongs_to :model_visitum, optional: true
end

app/models/country.rb
class Country < ApplicationRecord
    self.table_name = "countries"
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/lugar.rb
class Lugar < ApplicationRecord
    has_one_attached :image_place
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #has_many :lugars, :through => :model_visitums
  #validates :email, :presence => true, :email => true
  has_many :model_visitums , :foreign_key => :id_usuario
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
  has_one_attached :avatar
  has_many :lugars, :foreign_key => :id_usuario
end

app/models/model_visitum.rb
class ModelVisitum < ApplicationRecord
    belongs_to :model , :foreign_key => :id_usuario
    belongs_to :lugar, :foreign_key => :id_lugar
    has_many :categorias,:foreign_key =>  :model_visita_id,dependent: :destroy
    accepts_nested_attributes_for :categorias, allow_destroy: true
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/ahorros_controller.rb
class AhorrosController < ApplicationController
  before_action :set_ahorro, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'
  # GET /ahorros
  # GET /ahorros.json
  def index
    @ahorros = Ahorro.all
  end

  # GET /ahorros/1
  # GET /ahorros/1.json
  def show
  end

  # GET /ahorros/new
  def new
    @ahorro = Ahorro.new
  end

  # GET /ahorros/1/edit
  def edit
  end

  # POST /ahorros
  # POST /ahorros.json
  def create
    @ahorro = Ahorro.new(ahorro_params)

    respond_to do |format|
      if @ahorro.save
        format.html { redirect_to "/#dashboard", notice: 'Ahorro was successfully created.' }
        format.json { render :show, status: :created, location: @ahorro }
      else
        format.html { render :new }
        format.json { render json: @ahorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ahorros/1
  # PATCH/PUT /ahorros/1.json
  def update
    respond_to do |format|
      if @ahorro.update(ahorro_params)
        format.html { redirect_to "/#dashboard", notice: 'Ahorro was successfully updated.' }
        format.json { render :show, status: :ok, location: @ahorro }
      else
        format.html { render :edit }
        format.json { render json: @ahorro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ahorros/1
  # DELETE /ahorros/1.json
  def destroy
    @ahorro.destroy
    respond_to do |format|
      format.html { redirect_to ahorros_url, notice: 'Ahorro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ahorro
      @ahorro = Ahorro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ahorro_params
      params.require(:ahorro).permit(:id_viaje, :fecha_deposito, :cantidad)
    end
end

app/controllers/lugars_controller.rb
class LugarsController < ApplicationController
  before_action :set_lugar, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'
  # GET /lugars
  # GET /lugars.json
  def index
    @lugars = Lugar.all
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # GET /lugars/1
  # GET /lugars/1.json
  def show
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # GET /lugars/new
  def new
    @lugar = Lugar.new
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # GET /lugars/1/edit
  def edit
    @user = current_model
    @pais = Country.where(id: @user.pais)
  end

  # POST /lugars
  # POST /lugars.json
  def create
    @lugar = Lugar.new(lugar_params)
    respond_to do |format|
      if @lugar.save
        format.html { redirect_to @lugar, notice: 'Lugar was successfully created.' }
        format.json { render :show, status: :created, location: @lugar }
      else
        format.html { render :new }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugars/1
  # PATCH/PUT /lugars/1.json
  def update
    respond_to do |format|
      if @lugar.update(lugar_params)
        format.html { redirect_to @lugar, notice: 'Lugar was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugar }
      else
        format.html { render :edit }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugars/1
  # DELETE /lugars/1.json
  def destroy
    @lugar.destroy
    respond_to do |format|
      format.html { redirect_to lugars_url, notice: 'Lugar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lugar
      @lugar = Lugar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lugar_params
      params.require(:lugar).permit(:id_pais, :nombre,:image_place,:id_usuario)
    end
end

app/helpers/ahorros_helper.rb
module AhorrosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/model_visita_helper.rb
module ModelVisitaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!--  App Page-->
<!DOCTYPE HTML>
<!--
	Astral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title> Floppy  </title>
  <%= favicon_link_tag 'app.png'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'formulario' %>
  <%= csrf_meta_tags %>
  <script src="https://kit.fontawesome.com/306a9a7b97.js" crossorigin="anonymous"></script>
	</head>
	<body class="is-preload home">
		<!-- Wrapper-->
			<div id="wrapper">
				<!-- Main -->
					<div id="main">

						<!-- Me -->
							<article id="home" class="panel intro">
								<header>
									<% if model_signed_in? %>
									<h1>Welcome <%= current_model.email %></h1>
									<%= link_to "Log out", destroy_model_session_path, method: :delete %>
									<% else%>
									<h1> <i class="fas fa-route"></i></h1>
									<p> A Tool For Admnistrate Your Resources To Achieve Travel Goals.</p>
									<% end %>
								</header>
								<div class="app icon">
									
									
									<%= image_tag("app.png", :alt => "rss feed") %>

								</div>
							</article>
						<!-- info -->
						<article id="info" class="panel card  card-cool">
						<section>
						 <p> Make monthly savings. To Finance Your Trips.</p>
						</section>
								
						</article>
						<!-- Contact -->
						    
							<article id="login" class="panel  card card-cool">
								<header>
									<h2>Sign Up / Log In </h2>
								</header>
								<%if !model_signed_in? %>
								
								<%= yield %>
								<%else%>
								<%= link_to "Sign out", destroy_model_session_path, :method => :delete %>
								<%end%>
							</article>
							
						<!-- New Trip section -->
						<article id="app" class="panel">
								<header>
									<%= yield %>
								</header>
								
						</article>

					</div>

				<!-- Footer -->
					<div id="footer">
						<ul class="copyright">
							<a style="background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@guilhermestecanella?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Guilherme Stecanella"><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg></span><span style="display:inline-block;padding:2px 3px">Guilherme Stecanella</span></a>
							<li>&copy; Made with  <i style="color:red" class="fas fa-heart"></i> by Hèctor Jacales </li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</div>
					<!-- Nav -->
					<nav id="nav">
					    <h1>Floppy</h1>
						<a href="/" class="icon solid fa-home"><i class="fas fa-home"></i></a>
						
						<% if !model_signed_in? %>
							<a href="#login" class="icon solid fa-envelope"> <i class="fas fa-sign-in-alt"></i> </a>
						<% else %>
						    <a href="#app" class="icon solid fa-envelope"> <i class="fas fa-plane-departure"></i></a>
						<% end %>
					</nav>

			</div>

		<!-- Scripts -->
      <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'util', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>

	</body>
	<style>
	 .home {
 		 background-image: url(<%= asset_path 'home.jpg' %>)  !important;
  		background-position: center !important;
  		background-repeat: no-repeat !important;
  		background-size: cover !important;
  		color: #fff !important;
 }
<style>
</html>

app/views/layouts/dashboard.html.erb
<!--  App Page-->
<!DOCTYPE HTML>
<!--
    RAILS_ENV=production bundle exec rake assets:precompile
	Astral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title> Floppy  </title>
  <%= favicon_link_tag 'app.png'%>		
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'formulario' %>
  <%= csrf_meta_tags %>
  <script src="https://kit.fontawesome.com/306a9a7b97.js" crossorigin="anonymous"></script>
	</head>
	<body class="is-preload">

		<!-- Wrapper-->
			<div id="wrapper">
				<!-- Main -->
					<div id="main">

						<!-- Me -->
							<article id="home" class="panel intro">
								<header>
									<% if model_signed_in? %>
									 <% if @user.nombre.nil? %>
									 <div>
									 <%= @user.email %>
									 <a href="/models/edit#app"> <h1> Complete your profile </h1> </a>
									 </div>
									 <% else  %>
									 	<h1>Welcome <%= @user.nombre %> | </h1> <h2>
										 <%= @pais[0].iso3 %>
										 </h2>
									 <% end %>
									<%= link_to  destroy_model_session_path, method: :delete,class: 'button-cool' do %>
									 <i class="fas fa-sign-out-alt"></i>
									<% end %>
									<% else%>
									<h1>Floppy </h1>
									<p> A Tool To Admnistrate Your Resources To Archive Travel Goals.</p>
									<% end %>
								</header>
								<a href="/models/edit#app" class="jumplink pic">
									<i class="fas fa-angle-right"></i>
									<% if model_signed_in? %>
									<% if !@user.avatar.attached? %>
										<%= image_tag("default_user-min.jpg", :alt => "rss feed") %>
									<% else %>
										<%= image_tag(@user.avatar, :alt => "rss feed") %>
								    <% end %>									
									<% else %>
									<%= image_tag("map-min.jpg", :alt => "rss feed") %>
									<% end %>
								</a>
							</article>

						<!-- Work -->
							<article id="dashboard" class="panel card card-cool">
								<header>
								     <% if model_signed_in?%>
									 <h2>Your Trips </h2>
									 <p></p>
									 <div class="row">
									 <% for viaje in  @user.model_visitums %>
									 <div class="col-4 col-6-medium col-12-small card-cool">
									     <% if !viaje.lugar.image_place.attached? %>
									     <%= link_to image_tag("wait-min.jpg", :alt => "rss feed"), edit_model_visitum_path(viaje)+"#new_trip", class: "image fit"  %>
										 <% else %>
										 	<%= link_to image_tag(viaje.lugar.image_place), dashboard_dashboard_path()+"?viaje=#{viaje.id}#new_trip", class: "image fit"%>
										 <% end %>
										 <b>Destination:</b> 
											 <%= link_to viaje.lugar.nombre ,edit_lugar_path(viaje)+"#new_trip" %></br>
										 Date: 	<%= link_to viaje.datetravel , edit_model_visitum_path(viaje)+"#new_trip"  %></br>
									 </div>
									 <% end %>
									 </div>
									 <% else %>
									<h2>App </h2>
									<% end %>
								</header>
								<p>
									
								</p>
								<section>
									<% if model_signed_in?%>
									
									<% else %>
									<div class="row">
										<div class="col-6 col-6-medium col-12-small">
											<a href="#" class="image fit"><%= image_tag("money-min.jpg", :alt => "rss feed") %></a>
										</div>
										
										<p><h4> Save Money , Plan Your Trip , Make it Real!  </h4>
                                        </p>
										<p> This is a tool to schedule your trips. Based on price of planes, hotels
										and documentation needed to travel. Yo can calculate and monitorite your saves,
										to make those trips somethin real. 
										</p>
									<% end %>
								</section>
							</article>

						<!-- Contact -->
						
							<article id="contact" class="panel">
								<header>
									<h2>Sign Up / Log In </h2>
								</header>
								<%if !model_signed_in? %>
								<a href="/models/sign_in"><input type="submit" value ="Login"></a>
								<a href="/models/sign_up"><input type="submit" value ="Sign up"></a>
								<%else%>
								<%= link_to "Sign out", destroy_model_session_path, :method => :delete %>
								<%end%>
							</article>
						<!-- New Trip section -->
						<article id="new_trip" class="panel card card-cool">
								<header>
									<%= yield %>
								</header>
								
						</article>

					</div>

				<!-- Footer -->
					<div id="footer">
						<ul class="copyright">
							<li>&copy; Made with  <i style="color:red" class="fas fa-heart"></i> by Hèctor Jacales </li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</div>
				<!-- Nav -->
					<nav id="nav">
						<a href="/#" class="icon solid fa-home"><i class="fas fa-home"></i></a>
						<a href="/#dashboard" class="icon solid fa-folder"><i class="fas fa-briefcase"></i></a>
						<% if !model_signed_in? %>
							<a href="#contact" class="icon solid fa-envelope"> <i class="fas fa-sign-in-alt"></i> </a>
						<% else %>
						    <a href="#new_trip" class="icon solid fa-envelope"> <i class="fas fa-plane-departure"></i></a>
						<% end %>
					</nav>
			</div>

		<!-- Scripts -->
      <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'util', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>

	</body>
</html>

app/views/layouts/forms.html.erb
<!--  App Page-->
<!DOCTYPE HTML>
<!--
	Astral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title> Floppy  </title>
  <%= favicon_link_tag 'app.png'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'formulario' %>
  <%= csrf_meta_tags %>
  <script src="https://kit.fontawesome.com/306a9a7b97.js" crossorigin="anonymous"></script>
	</head>
	<body class="is-preload home">
		<!-- Wrapper-->
			<div id="wrapper">
				<!-- Main -->
					<div id="main">

						
						<article id="app" class="panel card card-cool">
								<header>
									<%= yield %>
								</header>
								
						</article>

					</div>

				<!-- Footer -->
					<div id="footer">
						<ul class="copyright">
							<a style="background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@guilhermestecanella?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Guilherme Stecanella"><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg></span><span style="display:inline-block;padding:2px 3px">Guilherme Stecanella</span></a>
							<li>&copy; Made with  <i style="color:red" class="fas fa-heart"></i> by Hèctor Jacales </li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</div>
					<!-- Nav -->
					<nav id="nav">
					    <h1>Floppy</h1>
						<a href="/" class="icon solid fa-home"><i class="fas fa-home"></i></a>
						
						<% if !model_signed_in? %>
							<a href="#login" class="icon solid fa-envelope"> <i class="fas fa-sign-in-alt"></i> </a>
						<% else %>
						    <a href="#app" class="icon solid fa-envelope"> <i class="fas fa-plane-departure"></i></a>
						<% end %>
					</nav>

			</div>

		<!-- Scripts -->
      <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'util', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>

	</body>
	<style>
	 .home {
 		 background-image: url(<%= asset_path 'home.jpg' %>)  !important;
  		background-position: center !important;
  		background-repeat: no-repeat !important;
  		background-size: cover !important;
  		color: #fff !important;
 }
<style>
</html>

app/views/layouts/trip.html.erb
<!--  App Page-->
<!DOCTYPE HTML>
<!--
    RAILS_ENV=production bundle exec rake assets:precompile
	Astral by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title> Floppy </title>
   <%= favicon_link_tag 'app.png'%>			
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'formulario' %>
  <%= csrf_meta_tags %>
  <script src="https://kit.fontawesome.com/306a9a7b97.js" crossorigin="anonymous"></script>
	</head>
	<body class="is-preload">

		<!-- Wrapper-->
			<div id="wrapper">
		
				<!-- Main -->
					<div id="main">

						<!-- Me -->
							<article id="home" class="panel intro">
								<header>
									<% if model_signed_in? %>
									 <% if @user.nombre.nil? %>
									 <div>
									 <%= @user.email %>
									 <a href="/models/edit#app"> <h1> Complete your profile </h1> </a>
									 </div>
									 <% else  %>
									 	<h1>Welcome <%= @user.nombre %> | </h1> <h2>
										 <%= @pais[0].iso3 %>
										 </h2>
									 <% end %>
									<%= link_to  destroy_model_session_path, method: :delete,class: 'button-cool' do %>
									 <i class="fas fa-sign-out-alt"></i>
									<% end %>
									<% else%>
									<h1>Floppy</h1>
									<p> A Tool To Admnistrate Your Resources To Archive Travel Goals.</p>
									<% end %>
								</header>
								<a href="/models/edit#app" class="jumplink pic">
									<i class="fas fa-angle-right"></i>
									<% if model_signed_in? %>
									<% if !@user.avatar.attached? %>
										<%= image_tag("default_user-min.jpg", :alt => "rss feed") %>
									<% else %>
										<%= image_tag(@user.avatar, :alt => "rss feed") %>
								    <% end %>									
									<% else %>
									<%= image_tag("icon.png", :alt => "rss feed") %>
									<% end %>
								</a>
							</article>

						<!-- Work -->
							<article id="dashboard" class="panel">
								<header>
								     <% if model_signed_in?%>
									 <h2>Your Trips!</h2>
									 <p></p>
									 <% if @user.model_visitums.empty?%>
									 <p>You have not any trips <a class="button-cool" href="#new_trip"> Add New Trip </a></p>
									 <% end %>
									 <div class="row">
									 <% for viaje in  @user.model_visitums %>
									 <div class="col-8 col-8-medium col-12-small card-cool card">
									     <% if !viaje.lugar.image_place.attached? %>
									     <%= link_to image_tag("wait-min.jpg", :alt => "rss feed"), dashboard_dashboard_path()+"?viaje=#{viaje.id}#new_trip", class: "image fit"  %>
										 <div class="card-panel">
										  <%= link_to dashboard_dashboard_path()+"?viaje=#{viaje.id}#new_trip",class: 'visit-button' do %>
										   <i class="fas fa-eye"></i>
										  <% end%>
										  <%= link_to  edit_model_visitum_path(viaje)+"#new_trip", class: 'edit-button' do %>
										  <i class="fas fa-edit"></i>
										  <% end %>
										  									 
										</div>
										 <% else %>
										    <% if viaje.status.nil? %>
										 	<%= link_to image_tag(viaje.lugar.image_place), dashboard_dashboard_path()+"?viaje=#{viaje.id}#new_trip", class: "image fit"%>
											<% else %>
											<%= link_to image_tag(viaje.lugar.image_place), dashboard_dashboard_path()+"?viaje=#{viaje.id}#new_trip", class: "image fit gray"%>
											<% end %>
										 <div class="card-panel">
										  <%= link_to dashboard_dashboard_path()+"?viaje=#{viaje.id}#new_trip",class: 'visit-button' do %>
										   <i class="fas fa-eye"></i>
										  <% end%>
										  <%= link_to  edit_model_visitum_path(viaje)+"#new_trip", class: 'edit-button' do %>
										  <i class="fas fa-edit"></i>
										  <% end %>
										  									 
										</div>
										 <% end %>
										 
										 <div class="info">
										 <% if !viaje.status.nil? %>
										   <p style="color:#000"> This trip has been booked</p>
										   <% end %>
										 <h2><%= link_to viaje.lugar.nombre ,edit_lugar_path(viaje.lugar)+"#new_trip" %></br></h2> 
											 Date: 	<%= link_to viaje.datetravel , edit_model_visitum_path(viaje)+"#new_trip"  %>
										<div id="tag">
										<% if viaje.lugar.id_pais == @user.pais%>
										 <b class="local">Local/National <i class="fas fa-flag"></i></b>
										 <% else %>
										 <b class="international">International <i class="fas fa-globe-europe"></i></b>
										 <% end %>
										</div>
										
										 </div>
										 
									 </div>
									 <% end %>
									 </div>
									 <% else %>
									<h2>App </h2>
									<% end %>
								</header>
								<p>
									
								</p>
								<section>
									<% if model_signed_in?%>
									
									<% else %>
									<div class="row">
										<div class="col-6 col-6-medium col-12-small">
											<a href="#" class="image fit"><%= image_tag("money-min.jpg", :alt => "rss feed") %></a>
										</div>
										<p><h4> Save Money , Plan Your Trip , Make it Real!  </h4>
                                        </p>
										<p> This is a tool to schedule your trips. Based on price of planes, hotels
										and documentation needed to travel. Yo can calculate and monitorite your saves,
										to make those trips somethin real. 
										</p>
									<% end %>
								</section>
							</article>

						<!-- Contact -->
						
							<article id="contact" class="panel">
								<header>
									<h2>Sign Up / Log In </h2>
								</header>
								<%if !model_signed_in? %>
								<a href="/models/sign_in"><input type="submit" value ="Login"></a>
								<a href="/models/sign_up"><input type="submit" value ="Sign up"></a>
								<%else%>
								<%= link_to "Sign out", destroy_model_session_path, :method => :delete %>
								<%end%>
							</article>
						<!-- New Trip section -->
						<article id="new_trip" class="panel">
								<header>
									<h2> Add New Trip  </h2>
									<p></p>
									<a class="button-cool" href="/lugars/new#new_trip" class="cool-button"> New Arrival Place <i class="fas fa-map-marker-alt"></i> </a>
									<a class="button-cool" href="/model_visita/new#new_trip" class="cool-button">  Plan New Tripp <i class="fas fa-money-check-alt"></i></a>
									<%= yield %>
								</header>
								
						</article>

					</div>

				<!-- Footer -->
					<div id="footer" class="black">
						<ul class="copyright">
							<li>&copy; Made with  <i style="color:red" class="fas fa-heart"></i> by Hèctor Jacales </li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</div>
				<!-- Nav -->
					<nav id="nav">
						<a href="/#" class="icon solid fa-home"><i class="fas fa-home"></i></a>
						<a href="/#dashboard" class="icon solid fa-folder"><i class="fas fa-briefcase"></i></a>
						<% if !model_signed_in? %>
							<a href="#contact" class="icon solid fa-envelope"> <i class="fas fa-sign-in-alt"></i> </a>
						<% else %>
						    <a href="#new_trip" class="icon solid fa-envelope"> <i class="fas fa-plane-departure"></i></a>
						<% end %>
					</nav>	

			</div>

		<!-- Scripts -->
      <%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'util', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>

	</body>
</html>